# Generated by Django 3.2.8 on 2021-10-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('current_count', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Текущий счет')),
                ('all_count', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма покупок')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Потолок кредита')),
                ('current_credit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Текущий кредит')),
                ('left_credit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Остаток кредита')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_needed_product', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('pay_way', models.CharField(choices=[('be', 'balance'), ('ct', 'credit'), ('br', 'barter')], max_length=255)),
                ('cost_of_given_product', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Покупатель')),
                ('given_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_product', to='mainapp.product', verbose_name='Отдаваемый продукт')),
                ('needed_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_product', to='mainapp.product', verbose_name='Запаришваемый продукт')),
            ],
        ),
    ]
