# Generated by Django 3.2.8 on 2021-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_order_cost_of_given_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_of_given_product',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество отдаваемого продукта'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_of_needed_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество нужного товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cost_of_given_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость отдаваемого продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost_of_needed_product',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость нужного товара'),
        ),
    ]
