# Generated by Django 3.2.8 on 2021-10-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211010_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost_of_given_product',
            new_name='given_cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity_of_given_product',
            new_name='given_quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cost_of_needed_product',
            new_name='needed_cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity_of_needed_product',
            new_name='needed_quantity',
        ),
    ]
