# Generated by Django 3.2.8 on 2021-10-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211011_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Текущий кредит'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_way',
            field=models.CharField(choices=[('be', 'Оплата'), ('ct', 'Кредит'), ('br', 'Бартер')], max_length=255),
        ),
    ]
