# Generated by Django 3.2.8 on 2021-10-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211011_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='given_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Стоимость отдаваемого продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needed_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Стоимость нужного товара'),
        ),
    ]
