# Generated by Django 3.2.8 on 2021-10-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211011_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='given_quantity',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Количество отдаваемого продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_way',
            field=models.CharField(choices=[('cash', 'Наличный расчет'), ('cashless', 'Безналичный расчет'), ('credit', 'Кредит'), ('barter', 'Бартер')], max_length=255),
        ),
    ]
