# Generated by Django 3.2.8 on 2021-10-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211011_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='all_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Сумма покупок'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Текущий счет'),
        ),
    ]
