# Generated by Django 3.2.8 on 2021-10-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='given_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость отдаваемого продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='given_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество отдаваемого продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Стоимость нужного товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needed_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_product', to='mainapp.product', verbose_name='Запаришваемый продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needed_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество нужного товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_way',
            field=models.CharField(choices=[('cash', 'Наличный расчет'), ('cashless', 'Безналичный расчет'), ('credit', 'Кредит'), ('barter', 'Бартер'), ('sell', 'Взаимозачет')], max_length=255, verbose_name='способ оплаты'),
        ),
    ]
