# Generated by Django 3.2.8 on 2021-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211012_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='low_left_credit',
            field=models.BooleanField(default=False, verbose_name='Низкий остаток кредита'),
        ),
    ]
