# Generated by Django 3.2.8 on 2021-10-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_customer_low_left_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='low_left_credit',
            field=models.BooleanField(default=False, editable=False, verbose_name='Низкий остаток кредита'),
        ),
    ]
