# Generated by Django 3.2.8 on 2021-10-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_customer_low_left_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='editing',
            field=models.BooleanField(default=True, verbose_name='В процессе создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needed_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_product', to='mainapp.product', verbose_name='Запрашиваемый продукт'),
        ),
    ]
