# Generated by Django 3.2.8 on 2021-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20211012_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='editing',
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Создан'),
        ),
    ]
